2024-12-15 20:08:09,885 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Python__Lessones\Module_12\tests_12_4\tests_12_4.py", line 73, in test_run
    runner_2 = Runner(3)
               ^^^^^^^^^
  File "C:\Users\User\Desktop\Python__Lessones\Module_12\tests_12_4\tests_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-15 20:08:09,886 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Python__Lessones\Module_12\tests_12_4\tests_12_4.py", line 62, in test_walk
    runner_1 = Runner('Вася', -5)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Python__Lessones\Module_12\tests_12_4\tests_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
